### ISSUE TITLE
Backend - Create fake data on the database

### ISSUE THREAD

**Issue by h-khalaf** [IMS-Group-7/Backend#13]
### Description of the task
It can be useful to create fake data to test out different features and user interfaces. Developers can experiment with different design ideas and functionality without having to wait for real data.

---

### User story
As a developer, I want to test features without waiting for real data

---

### Definitions of Done
- [x] Fake but coherent data is created on the database, based on predefined rules and parameters

**Comment by boiledsauce** [comment]
Fixed
