### ISSUE TITLE
Modify the backend to use web sockets

### ISSUE THREAD

**Issue by fluffyloafie** [IMS-Group-7/Backend#15]
### Description of the task
To connect the mobile app and the robot, we will use web sockets, relayed by the backend. The backend has to be adapted to this use

---

### User story
As a developer, I want to use the backend to communicate between the mobile app and the robot

---

### Definitions of Done

- [x] Setup a socket server
- [x] All necessary event listeners are implemented and documented
- [x] The feature is tested

**Comment by h-khalaf** [comment]
[SocketIO](https://socket.io/) was implemented instead of a normal web socket server.

**Comment by h-khalaf** [comment]
I think this should be done now. In the near future, we will probably make small changes to see how it fits the whole project :)
