### ISSUE TITLE
Document REST API endpoints

### ISSUE THREAD

**Issue by fluffyloafie** [IMS-Group-7/Backend#31]
### Description of the task
Document each endpoint, potential error codes, and success responses

---

### User story
As a developer, I want a comprehensive documentation of all REST API endpoints in the backend

---

### Definitions of Done
- [x] REST API endpoints are clearly documented, including:
    - [x] Endpoint name and purpose- Potential error codes and success responses for each endpoint are documented,
    - [x] Examples of correct usage and expected responses are provided for each endpoint

**Comment by boiledsauce** [comment]
The endpoints needs to be refined more, it is missing error codes.
