### ISSUE TITLE
Document Backend

### ISSUE THREAD

**Issue by fluffyloafie** [IMS-Group-7/Backend#32]
### Description of the task
Document the architecture of the backend, how the Google API is being used, what database is used and more.

---

### User story
As a developer, I want a detailed documentation of the backend architecture, including components and their interactions

---

### Definitions of Done
- [x] Backend components are clearly documented, including:
    - [x] Interactions and data flow between components,
    - [x] External Google services & API:s used
    - [x] Database schema, tables, and relationships
    - [x] Architectural overview

**Comment by boiledsauce** [comment]
Need to modify the architecture picture once.
